
import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
    { amharicName: "የተለጠፈ ሻይን በዘለበት", name: "Laminated Shine with Buckle", code: "0011" },
    { amharicName: "የተለጠፈ በተሰኪ", name: "Laminated with Pin", code: "0012" },
    { amharicName: "የተለጠፈ ኦርጅናል ታሳሪ", name: "Laminated Original Fastener", code: "0013" },
    { amharicName: "የተለጠፈ ቆርቆሮ ታሳሪ", name: "Laminated Tin Fastener", code: "0014" },
    { amharicName: "ደበል ፌስ በተሰኪ", name: "Double Face with Pin", code: "0015" },
    { amharicName: "ደብል ፌስ በኦርጅናል ታሳሪ", name: "Double Face with Original Fastener", code: "0016" },
    { amharicName: "ደብል ፌስ በቆርቆሮ ዘለበት", name: "Double Face with Tin Buckle", code: "0017" },
    { amharicName: "የተለጠፈ ላኮስት", name: "Laminated Lacoste", code: "0018" },
    { amharicName: "ቀጭን የተለጠፈ ቆርቆሮ", name: "Thin Laminated Tin", code: "0019" },
    { amharicName: "የተለጠፈ የጂኬ", name: "Laminated GK", code: "0020" },
    { amharicName: "የተለጠፈ የትንሹ ተሰኪ", name: "Laminated Small Pin", code: "0021" },
    { amharicName: "ቆዳ ወጥ classic ሰፊ", name: "Solid Leather Classic Wide", code: "0022" },
    { amharicName: "ቆዳ classic ቅጥል ሰፊ", name: "Joined Leather Classic Wide", code: "0023" },
    { amharicName: "ቆዳ ወጥ ሰፊ", name: "Solid Leather Wide", code: "0024" },
    { amharicName: "ቆዳ ሰፊ ቅጥል", name: "Joined Leather Wide", code: "0025" },
    { amharicName: "ቆዳ ወጥ መሀከለኛ", name: "Solid Leather Medium", code: "0026" },
    { amharicName: "ቆዳ ቅጥል መሀከለኛ", name: "Joined Leather Medium", code: "0027" },
    { amharicName: "jk ቆዳ ታሳሪ", name: "JK Leather Fastener", code: "0028" },
    { amharicName: "jk ቆዳ ቅጥል", name: "JK Joined Leather", code: "0029" },
    { amharicName: "Lacost ቆዳ ወጥ", name: "Lacoste Solid Leather", code: "0030" },
    { amharicName: "Lacost ቆዳ ቅጥል", name: "Lacoste Joined Leather", code: "0031" },
    { amharicName: "Lacost ቆዳ ማፈኛ", name: "Lacoste Leather Choke", code: "0032" },
    { amharicName: "Lacost ቅጥል", name: "Lacoste Joined", code: "0034" },
    { amharicName: "ነካሽ classic", name: "Biter Classic", code: "0035" },
    { amharicName: "classic በዘለበት", name: "Classic with Buckle", code: "0036" },
    { amharicName: "Classic Automatic (ተከርባች)", name: "Classic Automatic", code: "0037" },
    { amharicName: "ሀዲድ classic", name: "Rail Classic", code: "111" },
    { amharicName: "ሀዲድ ሸራ", name: "Rail Canvas", code: "112" },
    { amharicName: "ሰዓት ሸራ", name: "Watch Canvas", code: "113" },
    { amharicName: "ፈርጥ ሸራ", name: "Gem Canvas", code: "114" },
    { amharicName: "መውጊያ ሸራ", name: "Stinger Canvas", code: "115" },
    { amharicName: "የሽርጥከለር ሸራ", name: "Shirț Color Canvas", code: "116" },
    { amharicName: "የሽርጥ 1ኛ ሸራ", name: "Shirț 1st Canvas", code: "117" },
    { amharicName: "የሽርጥ 2ኛ ሸራ", name: "Shirț 2nd Canvas", code: "118" },
    { amharicName: "ተካፋች ሸራ", name: "Divider Canvas", code: "119" },
    { amharicName: "ተቆላፊ ሸራ", name: "Lockable Canvas", code: "120" },
    { amharicName: "የልጅ በዘለበት", name: "Kids with Buckle", code: "121" },
    { amharicName: "Ok የታሸገ", name: "OK Sealed", code: "122" },
    { amharicName: "ok ያልታሸገ", name: "OK Unsealed", code: "123" },
    { amharicName: "ok መሀከለኛ", name: "OK Medium", code: "124" },
    { amharicName: "መስመር መሀከለኛ ሸራ", name: "Line Medium Canvas", code: "125" },
    { amharicName: "ባንድራ ሸራ", name: "Flag Canvas", code: "126" },
    { amharicName: "ጥቁር ወፍራም", name: "Black Thick", code: "211" },
    { amharicName: "ስፌት ገበር", name: "Stitch Cover", code: "212" },
    { amharicName: "ግሪን ቡሽ", name: "Green Bush", code: "213" },
    { amharicName: "ዜብራ ገበር", name: "Zebra Cover", code: "214" },
    { amharicName: "ዳባን ቆዳ", name: "Daban Leather", code: "215" },
    { amharicName: "ቅልቅል ቆዳ", name: "Mixed Leather", code: "216" },
    { amharicName: "ቅልቅል የልጅ ቆዳ", name: "Mixed Kids Leather", code: "217" },
    { amharicName: "ቡሽ ገበር", name: "Bush Cover", code: "218" },
    { amharicName: "ቶርሽን ጥቁር", name: "Torsion Black", code: "219" },
    { amharicName: "ቶርሽን ከለር", name: "Torsion Color", code: "220" },
    { amharicName: "ቶርሽን Sport", name: "Torsion Sport", code: "221" },
    { amharicName: "ጠቃጠቆ ከለር", name: "Freckle Color", code: "222" },
    { amharicName: "ደረቅ ቻይና", name: "Dry China", code: "223" },
    { amharicName: "Wallet ቆዳ ቦርሣ", name: "Wallet Leather Bag", code: "311" },
    { amharicName: "wallet ዙሪያው ስፌት", name: "Wallet Surrounding Stitch", code: "312" },
    { amharicName: "wallet ቦርሣ", name: "Wallet Bag", code: "313" },
    { amharicName: "Atm wallet", name: "ATM Wallet", code: "314" },
    { amharicName: "ቆዳ ቦርሣ 2ዚፕ", name: "Leather Bag 2 Zip", code: "315" },
    { amharicName: "ከለር ቦርሣ", name: "Color Bag", code: "316" },
    { amharicName: "የተለያየ ቦርሣ", name: "Various Bags", code: "317" },
    { amharicName: "Ledy bag", name: "Lady Bag", code: "318" },
    { amharicName: "*** Leather ተለጣፊ በተሰኪ", name: "Leather Sticker with Pin", code: "411" },
    { amharicName: "Leather ተለጣፊ በዘለበት", name: "Leather Sticker with Buckle", code: "412" },
    { amharicName: "Leather ተለጣፊ ላኮስት", name: "Leather Sticker Lacoste", code: "413" },
    { amharicName: "leater ቅጥል", name: "Joined Leather", code: "414" },
    { amharicName: "leather lacost ቅጥል", name: "Joined Leather Lacoste", code: "415" },
    { amharicName: "ስፌት ሌዘር ተሰኪ", name: "Stitch Leather Pin", code: "416" },
    { amharicName: "ስፌት ሌዘር በተሰኪ", name: "Stitch Leather with Pin", code: "417" },
    { amharicName: "ስፌት ሌዘር በዘለበት", name: "Stitch Leather with Buckle", code: "418" },
    { amharicName: "ስፌት ሌዘር ቅጥል", name: "Stitch Joined Leather", code: "419" },
    { amharicName: "ደብል ፌስ ሌዘር", name: "Double Face Leather", code: "420" },
];
